# permissions for end users to view recordns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: recordns-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pfsense-dns-controller
    app.kubernetes.io/part-of: pfsense-dns-controller
    app.kubernetes.io/managed-by: kustomize
  name: recordns-viewer-role
rules:
- apiGroups:
  - pfsense.rcluff.com
  resources:
  - recordns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pfsense.rcluff.com
  resources:
  - recordns/status
  verbs:
  - get
