# permissions for end users to view recordmxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: recordmx-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: output-dir
    app.kubernetes.io/part-of: output-dir
    app.kubernetes.io/managed-by: kustomize
  name: recordmx-viewer-role
rules:
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordmxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordmxes/status
  verbs:
  - get
