# permissions for end users to view recordaaaas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: recordaaaa-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: coredns-record-controller
    app.kubernetes.io/part-of: coredns-record-controller
    app.kubernetes.io/managed-by: kustomize
  name: recordaaaa-viewer-role
rules:
- apiGroups:
  - pfsense.rcluff.com
  resources:
  - recordaaaas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pfsense.rcluff.com
  resources:
  - recordaaaas/status
  verbs:
  - get
