---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recorda
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recorda/finalizers
  verbs:
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recorda/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordaaaas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordaaaas/finalizers
  verbs:
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordaaaas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordcnames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordcnames/finalizers
  verbs:
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordcnames/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordmxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordmxes/finalizers
  verbs:
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordmxes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordns/finalizers
  verbs:
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordsoa
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordsoa/finalizers
  verbs:
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordsoa/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordsrvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordsrvs/finalizers
  verbs:
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordsrvs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordtxts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordtxts/finalizers
  verbs:
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - recordtxts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - zones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coredns.rcluff.com
  resources:
  - zones/finalizers
  verbs:
  - update
- apiGroups:
  - coredns.rcluff.com
  resources:
  - zones/status
  verbs:
  - get
  - patch
  - update
