---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pfsense.rcluff.com
  resources:
  - dnsentries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pfsense.rcluff.com
  resources:
  - dnsentries/finalizers
  verbs:
  - update
- apiGroups:
  - pfsense.rcluff.com
  resources:
  - dnsentries/status
  verbs:
  - get
  - patch
  - update
