apiVersion: coredns.rcluff.com/v1
kind: RecordMX
metadata:
  labels:
    app.kubernetes.io/name: recordmx
    app.kubernetes.io/instance: recordmx-sample
    app.kubernetes.io/part-of: output-dir
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: output-dir
  name: recordmx-sample
spec:
  # TODO(user): Add fields here
