apiVersion: coredns.rcluff.com/v1
kind: RecordSRV
metadata:
  labels:
    app.kubernetes.io/name: recordsrv
    app.kubernetes.io/instance: recordsrv-sample
    app.kubernetes.io/part-of: output-dir
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: output-dir
  name: recordsrv-sample
spec:
  # TODO(user): Add fields here
