apiVersion: pfsense.rcluff.com/v1
kind: RecordAAAA
metadata:
  labels:
    app.kubernetes.io/name: recordaaaa
    app.kubernetes.io/instance: recordaaaa-sample
    app.kubernetes.io/part-of: coredns-record-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coredns-record-controller
  name: recordaaaa-sample
spec:
  # TODO(user): Add fields here
